### ISSUE TITLE
geoserver 2.9.x and 2.9.x-oauth2 reversed on official repo

### ISSUE THREAD

**Issue by gt-novelt** [geosolutions-it/geoserver#102]
It seams that  _**geoserver-2.9.x.war**_ and _**geoserver-2.9.x-oauth2.war**_ are reversed on the new official repository. Same goes with _**data-2.9.x.zip**_ and _**data-2.9.x-oauth2.zip**_.

https://build.geo-solutions.it/geonode/geoserver/latest/geoserver-2.9.x.war
https://build.geo-solutions.it/geonode/geoserver/latest/geoserver-2.9.x-oauth2.war

https://build.geo-solutions.it/geonode/geoserver/latest/data-2.9.x.zip
https://build.geo-solutions.it/geonode/geoserver/latest/data-2.9.x-oauth2.zip

![image](https://user-images.githubusercontent.com/37072369/50679858-81cbaa80-1005-11e9-9115-d3de1568a59e.png)

**Comment by simboss** [comment]
This kind of issues should go to the GeoServer JIRA [here](https://osgeo-org.atlassian.net/projects/GEOS/summary).
