### ISSUE TITLE
Add MetadataMap to StyleInfo

### ISSUE THREAD

**Issue by mbarto** [geosolutions-it/geoserver#111]
Most of the catalog info objects have a MetadataMap to store metadata.
StyleInfo (StyleInfoImpl) misses that.
It would be useful to add it, so that we can append metadata to styles (title, description) to be used by clients.
The metadata should be properly serialized (saved/loaded) in GS catalog and be updatable / readable by the REST APIs.

**Comment by simboss** [comment]
@fernandor777 we need an estimate for this as well as a plan of action.

Ideally we would need to backport this change to 2.15 for GeoNode.

**Comment by fernandor777** [comment]
On investigation(fast prototype) adding metadataMap filed to StyleInfo and StyleInfoImple enables Geoserver to serve and persist metadata on styles Rest items.

Plan:
- Add MetadataMap field to StyleInfoImpl class and StyleInfo interface.
- Add Rest integration tests.
- Live tests with Geoserver and curl.
- Backporting.

Estimate: 3 hours.

**Comment by simboss** [comment]
I will need this to be backported to 2.15 as we need for the geonode integration.

@aaime do you think we have issues with this backport?

**Comment by aaime** [comment]
I don't see a problem, it's new functionality that should not cause side effects, the usual 1 month cooldown applies though.

**Comment by simboss** [comment]
We need this before the geonode relase (half June).

Ideally asap so we can test it thoroughly.

**Comment by simboss** [comment]
@fernandor777 keep @allyoucanmap and @afabiani in the loop as they need to test this

**Comment by fernandor777** [comment]
Ok, working on it.

**Comment by simboss** [comment]
@mbarto @aaime there is a PR out for this [here](https://github.com/geoserver/geoserver/pull/3489) make sure you review and we close this as it is needed by the GeoNode integration.

Ideally we would need this on the 2.15.x.
Keep @afabiani and @allyoucanmap  in the loop.
