### ISSUE TITLE
Backport GEOS-9361 to 2.1.6.x

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/geoserver#123]
[Here](https://github.com/geoserver/geoserver/pull/3814) is the PR merged on master.
[Here](https://github.com/geoserver/geoserver/wiki/GSIP-181) is the proposal.

USual procedure:
1. ask the devel list, mention thatn more than 1 month has passed since the merge on master and that we have ben using this in a custom build so we are confident
2. once people respond, cherry pick the changes to the 2.16. x branch and make a PR
3. follow the PR until is done

I would want to see the progress logged on this issue so that I know where we are.

**Comment by imranrajjad** [comment]
email sent on developer ML

**Comment by imranrajjad** [comment]
2.16.x PR : https://github.com/geoserver/geoserver/pull/3923

**Comment by simboss** [comment]
did you do a full build plus some quick testing for this?

**Comment by imranrajjad** [comment]
full build, yes
quick testing, no, I am not really not aware of the functionality/feature but I can spend some time on it to confirm.

**Comment by simboss** [comment]
k

**Comment by imranrajjad** [comment]
@simboss  tested on 2.16.x, its good to go
