### ISSUE TITLE
ADMIN_ROLE is assigned by default if no role is returned for a user inside WebService Body Response

### ISSUE THREAD

**Issue by nmco** [geosolutions-it/geoserver#150]
GeoServer JIRA ticket:
https://osgeo-org.atlassian.net/browse/GEOS-9484

Let's keep the discussion on this issue for the moment.

As usual let's spend a couple of hours for an initial investigation (if more time is required lets discuss) and propose a plan whit estimate for this.

**Comment by taba90** [comment]
Pull request https://github.com/geoserver/geoserver/pull/4027

**Comment by nmco** [comment]
Merged https://osgeo-org.atlassian.net/browse/GEOS-9484, please backport @taba90 :back:.

**Comment by nmco** [comment]
@taba90 we need this backported to 2.16.x and 2.15.x, since this is a bug fix we can go ahead.

**Comment by taba90** [comment]
@nmco here prs: 2.16.x https://github.com/geoserver/geoserver/pull/4028
2.15.x https://github.com/geoserver/geoserver/pull/4029
