### ISSUE TITLE
GeoServer "system-status" {json,xml} endpoints do not return values anymore

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/geoserver#151]
Captured in [GEOS-9485](https://osgeo-org.atlassian.net/browse/GEOS-9485)

**Comment by simboss** [comment]
@nmco can yuo groom this one.

It comes from GeoNode integration, I verified it on our master deployment at [this link](http://cloudsdi.geo-solutions.it/geoserver/web/).

The output is here below and it does not contains the values.

[system-status.txt](https://github.com/geosolutions-it/geoserver/files/4155865/system-status.txt)

**Comment by simboss** [comment]
The fix should be backported to 2.16 as well.

**Comment by taba90** [comment]
At some point after 2.15.2 the creation of an object  of type [ValueHolder ](https://github.com/geoserver/geoserver/blob/198df2516aedbd06494615dca3084a406b36932f/src/main/src/main/java/org/geoserver/system/status/MetricValue.java#L151), needed for xml and json encoding, has been removed from the setValue method inside [MetricValue.java](https://github.com/geoserver/geoserver/blob/198df2516aedbd06494615dca3084a406b36932f/src/main/src/main/java/org/geoserver/system/status/MetricValue.java) thus leading to the missing value field in the response. Fix should be simple as putting it back there.

**Comment by nmco** [comment]
Yes @taba90 looks like you are correct, and looks like it was removed by mistake ([during the module promotion from community to core](https://github.com/geoserver/geoserver/commit/6d54024fe550543aa81226aacad6c06504af657c)).

That say, this should have been catch [by the integration tests](https://github.com/geoserver/geoserver/blob/e967d0f76517e9245d1167f5bbe8a1c4cedc0ae2/src/main/src/test/java/org/geoserver/system/status/SystemInfoCollectorTest.java), so please add a good test for this one.

The following tests class are available for this module:

- [SystemStatusMonitorPanelTest](https://github.com/geoserver/geoserver/blob/e967d0f76517e9245d1167f5bbe8a1c4cedc0ae2/src/web/core/src/test/java/org/geoserver/web/system/status/SystemStatusMonitorPanelTest.java#L19)
- [SystemInfoCollectorTest](https://github.com/geoserver/geoserver/blob/e967d0f76517e9245d1167f5bbe8a1c4cedc0ae2/src/main/src/test/java/org/geoserver/system/status/SystemInfoCollectorTest.java)
- [MonitorRestTest](https://github.com/geoserver/geoserver/blob/198df2516aedbd06494615dca3084a406b36932f/src/restconfig/src/test/java/org/geoserver/rest/system/status/MonitorRestTest.java#L61)

**Comment by nmco** [comment]
What's your estimate for this @taba90?

**Comment by nmco** [comment]
@simboss on which project shoudl the time for this one be logged?

**Comment by taba90** [comment]
pull request https://github.com/geoserver/geoserver/pull/4030

**Comment by nmco** [comment]
Review added, there is something to fix :smile:, you can then backport to 2.16.x right away.
