### ISSUE TITLE
Bump spring dependencies - security vulnerabilities

### ISSUE THREAD

**Issue by afabiani** [geosolutions-it/geoserver#152]
- [critical] Bump spring-security-oauth2 from 2.0.16.RELEASE to 2.0.18.RELEASE in /geoserver
 - [high severity] Bump spring.version from 5.1.1.RELEASE to 5.2.3.RELEASE in /geoserver

**Comment by simboss** [comment]
@afabiani I have moved this to the GeoServer repo. Open issues here next time.

**Comment by simboss** [comment]
@nmco let's discuss this with @aaime as well.

Apparently this is marked as a security threat from Github bot.

**Comment by simboss** [comment]
Feedback from @aaime:

> I beleive we need to take the existing PRs made by dependeabot, separate for spring and spring-security, mxi them into one, fix whatever tests are failing
and make sure they are using versions that are aligned in the two cases
which might be tricky... we need to see if a bugfix upgrade is enough, or we need to bump from spring 5.1 to 5.2 (minor version upgrade)

The PRs we ar ementioning, were we can find them @afabiani ?

**Comment by afabiani** [comment]
1. [Bump spring.version from 5.1.1.RELEASE to 5.2.3.RELEASE in /src](https://github.com/geoserver/geoserver/pull/4002)
2. [Bump spring.security.version from 5.1.5.RELEASE to 5.2.1.RELEASE in /src](https://github.com/geoserver/geoserver/pull/3949)
3. [Bump spring-security-oauth2 from 2.0.16.RELEASE to 2.0.18.RELEASE in /geoserver](https://github.com/GeoNode/geoserver-geonode-ext/pull/73)

**NOTE:** The last one is not detected by dependabot on GeoServer repo by only on the GeoServer project build for GeoNode [one](https://github.com/GeoNode/geoserver-geonode-ext). This impacts the [GeoServer "security" community module](https://github.com/geoserver/geoserver/tree/master/src/community/security) only.
