### ISSUE TITLE
Backport notification plugin WFS-T fix

### ISSUE THREAD

**Issue by aaime** [geosolutions-it/geoserver#159]
See https://osgeo-org.atlassian.net/browse/GEOS-9238
Landed on master only

**Comment by simboss** [comment]
@nmco @aaime let's see who can we assign this.

This is not a super priority but since it is a fix I would do it as soon as possible as this fix has been done like ages ago.

**Comment by aaime** [comment]
@nmco doing the backport probably best check which tests fail before the backport, and see that there are no new failures with the change (the module unfortunately does not build, it's known).

**Comment by simboss** [comment]
@nmco @aaime I would then go beyond the simple backport and make an investigation for fixing the module as is.

**Comment by nmco** [comment]
I will ask @taba90 (Marco) help on this, I will discuss with him Monday about this.

**Comment by nmco** [comment]
What's the client \ project for this @aaime ?

**Comment by aaime** [comment]
I think the client is @simboss  :-p

**Comment by taba90** [comment]
Test are failing also on master. It is a class path issue:qpid dependecy used for test need a guava library with a different version from the one provided. After adding a different guava dependecy with the proper version and test scope test works bot on master, 2.17 and 2.16 (backported). I'm opening an issue on JIRA

**Comment by simboss** [comment]
keep us posted @taba90 

When you start working on something, please assign it to you.

**Comment by taba90** [comment]
Pull request https://github.com/geoserver/geoserver/pull/4143

**Comment by simboss** [comment]
what is the status on this one @taba90 ?

**Comment by taba90** [comment]
above pull request is waiting for the end of review, once merged I can backport that fix plus https://osgeo-org.atlassian.net/browse/GEOS-9238

**Comment by taba90** [comment]
class path issue fix has been merged on master. Here the backport for 2.17.x https://github.com/geoserver/geoserver/pull/4166
and the backport for 2.16.x https://github.com/geoserver/geoserver/pull/4167
according to the issue this last one comprise also https://osgeo-org.atlassian.net/browse/GEOS-9238

**Comment by taba90** [comment]
backport pull requests got merged

**Comment by simboss** [comment]
thx @taba90 closing this one
