### ISSUE TITLE
Trying to restore the layers, the default style is not set correctly

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/geoserver#160]
This issue seems to be happening on 2.16 train only.
Try to do a backup on a zip file of the catalog and later try to restore it.
The stores and layers are restored but on layers, the default style seems to be not correctly configured any more.

[GEOS-9530](https://osgeo-org.atlassian.net/browse/GEOS-9530)

**Comment by simboss** [comment]
@nmco let's brainstorm about who we can throw this at.

**Comment by simboss** [comment]
@giohappy what is the priority and timeline for this?

**Comment by giohappy** [comment]
Ideally I would like to have it fixed to migrate ADBPO to GeoNode 3 +
Geoserver 2.16.x

**Comment by nmco** [comment]
@giohappy I guess this is for:
```
WB-GFDRR
C080-WB-2019-AFGHANISTAN-SUPPORT
```

That say, looks like both this issues are strongly related:
* https://osgeo-org.atlassian.net/browse/GEOS-9530
* https://osgeo-org.atlassian.net/browse/GEOS-9537

There is a PR for ``GEOS-9537``, [that probably fixes this one too](https://github.com/geoserver/geoserver/pull/4123), can you @giohappy double check with @afabiani if that's indeed the case?

**Comment by giohappy** [comment]
@nmco yes, they're related. The PR should solve both of them.
I've asked @afabiani to link the PR to GEOS-9530 too

**Comment by simboss** [comment]
@nmco @giohappy check with @afabiani if he is already working on this or if this is similar to what he is already working on .

**Comment by giohappy** [comment]
@simboss see my comment above.

**Comment by simboss** [comment]
@giohappy I am confused, can we close this one or not.

**Comment by giohappy** [comment]
We're going to test the fix within the GN b/r procedure. So I think we can close this. In case of any issue reported during tests a new one will be created.
