### ISSUE TITLE
 Implement StandardDeviationFunction to classify vector data

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/geoserver#197]
This is a placeholder fo rimplementing STD classification in SLD Service for Vector data.

We need it on 2.17!

**Comment by taba90** [comment]
@simboss @giohappy Here the plan:

We have already a StandardDeviationFunction to classify vector data. What is missed is to call it form the RulesBuilder in the SLDService module.
For percentages the StandardDeviationFunction doesn't have any reference to class members numbers so it would be needed to make additional queries to the data to get them. Estimated time for this is 6 hours

**Comment by giohappy** [comment]
@taba90 I'm not able to make comments on the implementation details, but the estimate is fine for me, so please proceed.

**Comment by taba90** [comment]
working on this

**Comment by simboss** [comment]
@taba90 keep us posted

**Comment by taba90** [comment]
@simboss @giohappy  I made geotools and geoserver pull requests with the necessary changes. All details are availbale on the Jira ticket https://osgeo-org.atlassian.net/browse/GEOS-9703

**Comment by giohappy** [comment]
@simboss AFAICS the next release that can have the new functionality merged is 2.17.3, which will happen the 2020-09-18.
We'll need to wait the release, upgrade GeoNode to that version (the current one is 2.17.1) and finally deploy the new functionality to Almaviva. 

If we confirm this roadmap I will communicate it to he client.

**Comment by simboss** [comment]
if needed we can do a 2.17.2.1

**Comment by giohappy** [comment]
Let's see, but I think they could wait for 2.17.3...

**Comment by simboss** [comment]
Cool.

Always remember that we have the options to ad interim releases if we need it.
We have the rights and the resources to do them if needed.

**Comment by giohappy** [comment]
of course we need a test env for @allyoucanmap to test it from the styler.
Where / Who can do it @simboss ?

**Comment by simboss** [comment]
You need to clarify this with @allyoucanmap.

I think he can go away with a local WAR deploy, pretty much.

**Comment by giohappy** [comment]
one more thing. I suggested to add a REST endpoint that will return list of available methods. This would give the client (the styler in this case) the option to enable/disable some functionalities dynamically, otherwise we need ditinct styler versions for distinc SLD Service versions.

The logic could be:
 - if the endpoint doesn't exist the styler will expose the methods available to all the SLD versions
 - if the new endpoint is available the styler can inspect it and decide what to enable

@simboss if this doesn't take to much I would consider to implement it, or a similar mechanism.

**Comment by simboss** [comment]
@giohappy open a ticket under the root epic and define what you need.

We will ask   @taba90 an implementation plan and an estimate.

**Comment by giohappy** [comment]
I've simplified the request with this issue https://github.com/geosolutions-it/geoserver/issues/199

**Comment by simboss** [comment]
@taba90 status of this?

**Comment by taba90** [comment]
@simboss  geootools pr has been merged, here the backport https://github.com/geotools/geotools/pull/3101. waiting on the geoserver one to be merged too and be backported https://github.com/geoserver/geoserver/pull/4426, I've just pinged Andrea.

**Comment by taba90** [comment]
master pr merged on geoserver too. backport to 2.17.x produced https://github.com/geoserver/geoserver/pull/4448

**Comment by taba90** [comment]
backport merged too
