### ISSUE TITLE
Minor bug in style editor legend preview

### ISSUE THREAD

**Issue by nmco** [geosolutions-it/geoserver#203]
The bug is described [here](https://groups.google.com/g/geosolutions-helsinki/c/Ibylmjz6a7c/m/obAOazJXAwAJ), as usual let's start with the initial investigation (2 hours MAX).

**Comment by taba90** [comment]
By default geoserver doesn't draw label if only one rule is available. To make it render the label two it is necessary to use the `legendOptions `vendorParameter with `forceLabels:on` (
`http://localhost:8080/geoserver/ows?service=WMS&request=GetLegendGraphic&format=image%2Fpng&width=20&height=20&layer=Johtokartta_imujatehuolto_kaivo&LEGEND_OPTIONS=forceLabels:on`).
See also https://docs.geoserver.org/stable/en/user/services/wms/get_legend_graphic/index.html#controlling-legend-appearance-with-legend-options

**Comment by nmco** [comment]
Thx for the feedback @taba90, I think you missed one issue (Ville reported two), you missed the one about the Nordic characters:
![image](https://user-images.githubusercontent.com/1590542/92466615-43b65f00-f1c8-11ea-922f-959d6a029ef2.png)

**Comment by taba90** [comment]
substituting the encoding in the xml prolog fro  ISO-8859-1 if the sld files to UTF-8, led to a correct labels rendering.
`<?xml version="1.0" encoding="UTF-8"?>`
I've attached the fixed sld files.



[sld.zip](https://github.com/geosolutions-it/geoserver/files/5188420/sld.zip)

**Comment by nmco** [comment]
Thank you @taba90 !
