### ISSUE TITLE
Add address range in the GUI for rule definition in GeoFence embedded

### ISSUE THREAD

**Issue by chpicone** [geosolutions-it/geoserver#209]
We need to add in the GUI of GeoFence embedded the **addressRange** filter.

In the definition of a rule, to ALLOW/DENY (or LIMIT with WKT filter) specific IPs we need a textbox to make the admin able to configure an address range in CIDR notation:
![image.png](https://images.zenhubusercontent.com/5e98219c18069195a59f5217/bd6350b4-2bf7-40b7-9ba6-d615a3ab20a2)

**Comment by simboss** [comment]
@chpicone what is the status on this?

Can we close it?

**Comment by chpicone** [comment]
Yes we can close it.
