### ISSUE TITLE
Fix GeoFence Build

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/geoserver#210]
The GeoFence build has been failing for some time now.

We need to fix it asap since we have some work depending on it.
We might also need a new release soon, let's discuss plans once you get started with this.

**Comment by simboss** [comment]
On a second thought.
We should avoid depending on geotools snapshots and if possible an any snaphots at all.

**Comment by nmco** [comment]
I guess this is not relevant anymore? Can we close it?
