### ISSUE TITLE
GeoServer cannot show PARTITIONED table in PostGIS

### ISSUE THREAD

**Issue by chpicone** [geosolutions-it/geoserver#214]
If we have a (parent) partitioned table in postGIS (example TAB_A) we can see just the child tables (eg TAB_A_1, TAB_A_2, etc).

Tested on GeoServer 2.18.0.

[Here](https://osgeo-org.atlassian.net/browse/GEOT-6743) the JIRA ticket

**Comment by simboss** [comment]
We need to perform an investigation for implementing.

**Comment by simboss** [comment]
@aaime I just need an estimate and an implementation plan.

**Comment by aaime** [comment]
Subtypes? Hum... GeoTools would understand a partitioned table as a normal table and deliver just a single type out of it. If we are dealing with inheritance, then it seems to me we are talking about app-schema, and the rest of the response does not make sense.

I've seen usage of partitioned tables in a different context, as a way to speed up queries, if the filter manages to exclude entire partitions and possibly match only one or a handful. If that's the case, and PostgreSQL does not need any special way to query the partitioned table, then it's a matter of:
* Overriding, in both PostgisDialect and PostgisPSDialect, the ``getDesiredTablesType``, and make it include in the result list ``PARTITIONED TABLE`` as well.
* Adding a new test that creates a "PARTITIONED TABLE", makes sure it gets listed in the type names, and can be queried correctly (this is the time consuming part, one can look at ``PostGISCitextOnlineTest`` as a template).

Estimate wise, I'd guess between half a day and a day, depending on what experience the developers in charge has with the ``JDBCTestSupport``/``JDBCTestSetup`` testing framework.

**Comment by simboss** [comment]
@aaime can you liaise with @chpicone to make sure the scenario is clear as this is going to be part of next webinar I guess.

**Comment by aaime** [comment]
PR is out, here: https://github.com/geoserver/geoserver/pull/4586
Asked @afabiani for a review and switched this issue to the "review" column. 
Also asked Berhnard about the login/logout buttons and the automated build support.

**Comment by aaime** [comment]
Chatted with @chpicone, the subtypes have the same structure as the parent table, but different check constraints to maintain integrity, something that would pop up only when using WFS-T. So the estimate I've made above is all we need.

**Comment by simboss** [comment]
@aaime thake into account that we would need to backport this to 2.17.x for this project as we are using GeoNode.

Do you think it would be acceptable?

**Comment by aaime** [comment]
Yes, the actual code change is a line, it's just the test will take some effort.

**Comment by simboss** [comment]
Being a fix, we would need this to go as back as possible, until 2.17 I'd say.

This will have to be tested on GeoNode's GeoServer.

**Comment by aaime** [comment]
Changes merged on master and backported on 24.x and 23.x. Will be available starting with the January releases, onwards.

**Comment by simboss** [comment]
@aaime is it possible to isolate the JARs involved in this fix?

@chpicone this is for you...

**Comment by aaime** [comment]
Yes, only ``gt-jdbc-postgis-<version>.jar`` has been affected. It can be picked from a GeoServer nightly build (starting tomorrow, but I can force the nightlies to run sooner if needs be).

**Comment by simboss** [comment]
@aaime is this fix part of 2.17.4? I think so, right?

**Comment by aaime** [comment]
No, the backport missed the release by a couple of days.

**Comment by simboss** [comment]
ouch, @chpicone did you read this message from @aaime ?

This means we have discuss a little on how to upgrade Krihs GeoNode (separately from this issue).

**Comment by chpicone** [comment]
Can we update just the gt-jdbc-postgis-<version>.jar library?

**Comment by aaime** [comment]
I believe so, yes, it's the only one that has been changed, and I see no other changes after the partitioned table fix in gt-jdbc-postgis (nor in gt-jdbc). So it _should_ work. We can only make sure testing it out.
