### ISSUE TITLE
App-schema bug jdbcMultipleValue directive

### ISSUE THREAD

**Issue by taba90** [geosolutions-it/geoserver#219]
The jdbcMultipleValue directory doesn't work if in app-schema is defined a ClientProperty with xlink:href eg.:

`<AttributeMapping>
				  <targetAttribute>eposl:purpose</targetAttribute>
				  <encodeIfEmpty>true</encodeIfEmpty>
				  <jdbcMultipleValue>
					<sourceColumn>boreholeid</sourceColumn>
					<targetTable>purpose_view</targetTable>
					<targetColumn>bss_id</targetColumn>
					<targetValue></targetValue>
				  </jdbcMultipleValue>
					<ClientProperty>
						<name>xlink:href</name>
						<value>purpose_href</value>
					</ClientProperty>
					<ClientProperty>
						<name>xlink:title</name>
						<value>libelle</value>
					</ClientProperty>
				</AttributeMapping>`

but it will not encode the values.

The bug is caused by [this ](https://github.com/geotools/geotools/blob/93f891d836efb78651ceafdf8762b9bd6641ba7e/modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/DataAccessMappingFeatureIterator.java#L1566) line which if xlink href is inside the clientProperties will not remove void propertyName from value, that is done next to the highlight if block. At encoding time this will cause the ComplexAttribute to not be recognized as a valid Complex gml attribute ([here](https://github.com/geotools/geotools/blob/06feeeb0b5ccfb6645b7197324fef8e36c2eb1d0/modules/extension/xsd/xsd-core/src/main/java/org/geotools/xsd/Encoder.java#L566) causing the enconding of the clientProperty  to be skipped.
The fix proposed implies the removal of void Properties from the ComplexAttribute before the xlink href check will return true, allowing then the encoder to validate the element as a Complex Attribute.

The following issue affects both the single ClientProperty issue with xlink:href and the double ClientProperty issue since it is caused by the definition of the xlink:href attribute.
Estimated time for this is 2/3 hours.

When defining a ClientProperty after JDBCMultipleValueDirective, the resulting query to the db might result to be ambiguous in case of multiple clientProperty with the JDBCMultipleValueDirective are defined for the same FeatureTypeMapping and the respective table have a column name named equally. This has been reproduced with geoserver test data, not involves the current BRGM use case. To fix this the simpler way seems to me:

when the AppSchemaDataAccessConfigurator extracts ClientProperties if the AttributeMapping holds a JDBCMultipleValue, create a JoinPropertyName holding the alias for the targetTable.
the JoiningJDBCFeatureSource should automatically encode the column name with the alias prefix correctly.
estimate time for this is 4 hours

**Comment by taba90** [comment]
Made a pr one https://github.com/geotools/geotools/pull/3420

**Comment by nmco** [comment]
@fernandor777 can you review this fix?

**Comment by nmco** [comment]
@fernandor777 where are we with the review for this? We have been waiting for a week now.

**Comment by nmco** [comment]
Both PRs merged, please backport @taba90 and build a custom WAR for BRGM based on 2.17.2 tag with this fix.

**Comment by taba90** [comment]
@nmco copy pasting the issues found by Abdel:
```
1/ the configuration as is (attached) would not rise any exception (with json, geojson or gml output) i.e. href and title filled but it doesn’t bring multi-values but only the last value

2/when I add (uncomment) the targetValue param, I got the error "Misplaced object.\nMisplaced object." (on json, geojson and gml)

3/when I leave the target value param and ask only for the title (comment the href part) I got weird answer:
The json output: the 4 title are retrieved
The geojson output: only 2
The gml output: I get this error: “Failed to get property: owns\njava.util.ArrayList cannot be cast to org.opengis.feature.Property”
```
[This is the xsd schema being used ](https://data.geoscience.earth/def/eposl.xsd)
Initial investigation result:
seems to me all 
[jdbcMultipleValue.zip](https://github.com/geosolutions-it/geoserver/files/6285935/jdbcMultipleValue.zip)
xsd schema definition problems:
1. The xsd definition of the purpose  attribute doesn't defines a maxOccurs="unbounded" then the encoded purpose of value is only one. with the following element definition i got all the purpose values (onlyClientProprties file in the zip).
2. and 3.i got no exception, but the result in files "CommentedHrefWithTargetValue" where the targetValue is not encoded but the xlink:title is. My understanding is that is correct since the[ ReferenceType is meant for byreference](http://www.wmo.int/schemas/wmdr/1.0RC4/documentation/schemadoc/schemas/gmlBase_xsd/complexTypes/ReferenceType.html) only encoding, while target value is used for an inline value.
To encode the targetValue as an element content a different type needs to be defined in the xsd check in the zip the purposeType. The targetValue will be correctly encoded.

**Comment by nmco** [comment]
I have done a quick update to Abdel. 

So @taba90 we used a different XSD schema then what their using?

**Comment by nmco** [comment]
@Sylvain told me he is testing this.
