### ISSUE TITLE
Set Response Cache Headers in LayerGroups

### ISSUE THREAD

**Issue by nmco** [geosolutions-it/geoserver#223]
The new functionality is described [here](https://osgeo-org.atlassian.net/browse/GEOS-9759). We can find [here](https://drive.google.com/file/d/1OxVroNZRBjL08M15VnOdfRjx-7IzICtb/view?usp=sharing) a video demoing the same functionality for layers, the goal is to implement it for layer groups. The documentation for this functionality on layers is available [here](https://docs.geoserver.org/latest/en/user/data/webadmin/layers.html#http-settings).

A few code pointers:

- Wicket UI implementation of the functionality for layers is available [here](https://github.com/geoserver/geoserver/blob/de184b2f9ed9a844b5291dd163e772132a07689b/src/web/core/src/main/java/org/geoserver/web/publish/HTTPLayerConfig.java) and [here](https://github.com/geoserver/geoserver/blob/5d5227a8b54e43525235f8d136f0ecc4420954e7/src/web/core/src/main/java/org/geoserver/web/publish/HTTPLayerConfig.html).
- The wicket UI implementation is registered [here](https://github.com/geoserver/geoserver/blob/e86d34dc1afb4d522cc20e897ba96d62b6fb516a/src/web/core/src/main/java/applicationContext.xml#L283-L288) and then injected [here](https://github.com/geoserver/geoserver/blob/de184b2f9ed9a844b5291dd163e772132a07689b/src/web/core/src/main/java/org/geoserver/web/publish/PublishedConfigurationPage.java#L417-L446).
- When the HTTP caching is enabled it will have an impact in the way GeoServer cache tiles, we can search for usages of [this](https://github.com/geoserver/geoserver/blob/2894d58bc9a921ab0dfbdd59670670c2830514f3/src/main/src/main/java/org/geoserver/catalog/ResourceInfo.java#L39-L40) to find where the caching handling is implemented. 

Let's start by proposing a plan to implement this functionality and estimate which should include:
- The implementation of the functionality.
- GeoServer integration tests for the functionality.
- GeoServer documentation update.

**Comment by nmco** [comment]
Let's follow the usual workflow:

1. Time-box the initial investigation of the issue to 4 hours MAXIMUM.
2. Clarify the context of the task, make sure you have everything needed to move on.
3. Provide a plan and estimate to handle the reported issue, report on the issue.
4. Wait for the green light from the PM before moving on with the implementation.

**Comment by zvrablik** [comment]
@nmco  how should the new http layer config co-exists with individual layer http layer config? 
1. Should it be ignored and use specified value in layer group http layer config only
2. Use value specified in layer group config if defined or use existing implementation - iterating of all layers in layer group.
see here
https://github.com/geoserver/geoserver/blob/633a426612c1b7753df8dd9e9922c687046e77b3/src/gwc/src/main/java/org/geoserver/gwc/layer/GeoServerTileLayer.java#L1205-L1227

There should be created another bean and the existing  HTTPLayerConfig implementation will share the java class code and html file. The metadata/resource.metadata value will be provided as parameter to shared class.

I have talked to Andrea about other option - change the resource.metadata used in LayerInfo and metadata used in LayerGroups, but the names are different intentionally. 

Being able to use same metadata property name would allow sharing all code, just changing the bean class to 
<bean id="httpLayerConfigPanel" class="org.geoserver.web.publish.CommonPublishedConfigurationPanelInfo">

These values should be customized  - there would be two beans one for layers and one for layer groups or if possible used same names and share all HTTPLayerConfig.

estimates 
code 0.5 day
documentation + setup sphynx and latex  if needed 0.5 day
test code + manual testing - 0.5 day

Missing part - how to pass customized metadata / resource.metadata to the HTTPLayerConfig. I have asked Andrea for pointers per email as I don't know his working hours.

**Comment by zvrablik** [comment]
update, I have talked to Andrea,
1. subclassing should inherit the html file
2. use wicket:child  wicket:extend  , see GeoServerErrorPage
![Screenshot from 2021-04-23 10-39-21](https://user-images.githubusercontent.com/1183452/115846594-5c574a80-a422-11eb-93bf-848fec017027.png)
![Screenshot from 2021-04-23 10-38-54](https://user-images.githubusercontent.com/1183452/115846628-65481c00-a422-11eb-820a-f07baa8acdf3.png)
3. copy the html if nothing else works

**Comment by zvrablik** [comment]
hints from discussion with Andrea
[diff.txt](https://github.com/geosolutions-it/geoserver/files/6364095/diff.txt)

**Comment by nmco** [comment]
@zvrablik did you agree with @aaime on a technical plan? If yes what's the final estimate?

**Comment by zvrablik** [comment]
@nmco Should this be backported to any older branches?

**Comment by zvrablik** [comment]
updated estimates
initial investigation 10 hours
code 8 hours
documentation (+ setup sphynx and latex if needed) 4 hours
test code + manual testing - 4 hours
backports 2  hours
review 2 hours

**total time estimated  30 hours**

@aaime Do you agree with these estimates? 

I have there one question. Each layer could have its own cache headers. Now there will be new configuration option in layer group too. Currently the cache header timeout for layer group is computed as min value of all layers cache max age in the layer group [here](http://github.com/geoserver/geoserver/blob/633a426612c1b7753df8dd9e9922c687046e77b3/src/gwc/src/main/java/org/geoserver/gwc/layer/GeoServerTileLayer.java#L1205-L1227)

**Comment by aaime** [comment]
@zvrablik nice to see all items that should go in a review, some comments:
* Initial investigation is not an estimate, it has happened already. So if you spent 10 hours, that's it.
* Documentation, you don't need latex but you'll have to setup sphynx. With pypy or easy-install it's a matter of a minute, but you'll have to get up to speed about writing docs using that tool. [See the quickstart guide here.](https://docs.geoserver.org/latest/en/docguide/)
* Review seems a bit long, but it should include the time it will take you to address the feedback received.

Overall some items are a bit long but at the same time reasonable, since you're using some tools for the first time. Not sure you've checked how to handle setting the caching headers, layer groups are exploded into their component layers inside GetMapKvpReader, from that point on no map rendering code knows what layer groups even are. Means you'll have to take note of the caching headers at that point (during KVP parsing) and set the information later. Can use a Spring request context to keep track of that for example.

**Comment by zvrablik** [comment]
Thanks @aaime 
I am going to look at max-age settings in the wms. You are right I checked only the GWC path, where the max-age of layer group was already used.

**Comment by zvrablik** [comment]
Talked again about the GetMapKvpReader with Andrea,
here are steps we agreed for the implementation

1. I create metadata field in MapLayerInfo to be able to set there the timeout value set in the group layer configuration.
2. Requesting metadata from layer would return new metadata where values from MapLayerInfo take precedence.
3. getting the timeout from MapLayerInfo - it would override the layer info value if layer group info max age specified
4. using the Spring request context I keep as backup plan if I run into problems with the plan in points 1 - 3

**Comment by nmco** [comment]
[PR done](https://github.com/geoserver/geoserver/pull/5014), waiting for review:
https://osgeo-org.atlassian.net/browse/GEOS-9759

**Comment by zvrablik** [comment]
@aaime Andrea I would need help with the Integration test.

**Comment by zvrablik** [comment]
@aaime the pull request is ready for second review

**Comment by zvrablik** [comment]
pull request was merged into main branch

**Comment by simboss** [comment]
@nmco where are we with this one?

**Comment by simboss** [comment]
@nmco why you closed this?
I don't see my questions answered above either...

**Comment by nmco** [comment]
Sorry, @simboss missed your question, the work has been contributed. It's available since GeoServer 2.20.1.

**Comment by simboss** [comment]
@nmco is this documented?
If yes, where?

**Comment by nmco** [comment]
Yes, in the GeoServer LayerGroups configuration documentation page:
https://docs.geoserver.org/latest/en/user/data/webadmin/layergroups.html#http-settings
