### ISSUE TITLE
Add default gridsets with 512px tiles to GeoWebCache

### ISSUE THREAD

**Issue by aaime** [geosolutions-it/geoserver#226]

**Comment by aaime** [comment]
@simboss Merged on master, ready for tests.

**Comment by simboss** [comment]
https://github.com/geosolutions-it/MapStore2/issues/6590

**Comment by simboss** [comment]
@aaime testing on mapstore is done and the gridsets seem to align perfectly.

Can we backport to 2.18 as well as we discussed?
This will help us a lot also with GeoNode integration of both.

**Comment by aaime** [comment]
I can ask at the PSC meeting tomorrow. As a new feature, backport needs to be approved.

**Comment by simboss** [comment]
Hi Andrea,
go ahead and ask then we will see who we can ask to do the actual work.

Let me know here how it goes.

**Comment by aaime** [comment]
Yep.. thought you said so yesterday durning our meeting, maybe I got confused?

**Comment by simboss** [comment]
Not really, just read two comments above.

**Comment by aaime** [comment]
Backport is done
