### ISSUE TITLE
Templating support for GML

### ISSUE THREAD

**Issue by taba90** [geosolutions-it/geoserver#234]
@nmco commented on [Mon Aug 31 2020](https://github.com/geosolutions-it/C124-BRGM-2019-JSON-LD/issues/41)

BRGM ask us to estimate the implementation of templating support for GML, templating means everything: create a template referencing simple or complex features attributes, support for backwards mapping. The GML templating should be based on an XML templating, this will allow us to support things like an HTML templating.

---

@taba90 commented on [Mon Dec 21 2020](https://github.com/geosolutions-it/C124-BRGM-2019-JSON-LD/issues/41#issuecomment-748828713)

Implementation details for an xml template that will work for html and gml output format.
I would use[StAX](https://docs.oracle.com/javase/tutorial/jaxp/stax/why.html) to write the final output and to read the template and create the builderTree as it is a memory efficient streaming reader of an xml document. 

The current build creation mechanism could be refracted a bit to use an AbstractFactory to choose specific Builder factory according to the output format making the code more manteinable.

New Specific implementation of Dynamic and Static builder will be needed in order to handle the xml attribute case.

**Comment by nmco** [comment]
Plan discussed here, 4 days of work will be needed and 1 for the review and contirbution. Go ahead @taba90

**Comment by taba90** [comment]
made a pr to main details on the jira ticket https://osgeo-org.atlassian.net/browse/GEOS-10063

**Comment by taba90** [comment]
merged on main

**Comment by taba90** [comment]
backported to 2.19.x
