### ISSUE TITLE
JDBCMultipleaValue directive ClientProperty might result in ambiguous query

### ISSUE THREAD

**Issue by taba90** [geosolutions-it/geoserver#240]
When defining a ClientProperty after JDBCMultipleValueDirective, the resulting query to the db might result to be ambiguous  in case of multiple clientProperty with the JDBCMultipleValueDirective are defined for the same FeatureTypeMapping and the respective table have a column name named equally. This has been reproduced with geoserver test data, not involves the current BRGM use case. To fix this the simpler way seems to me:

- when the AppSchemaDataAccessConfigurator extracts ClientProperties if the AttributeMapping holds a JDBCMultipleValue, create a JoinPropertyName holding the alias for the targetTable.
- the JoiningJDBCFeatureSource should automatically encode the column name with the alias prefix correctly.
estimate time for this is **4 hours**

**Comment by taba90** [comment]
made a mastrer pr for this https://github.com/geotools/geotools/pull/3420

**Comment by nmco** [comment]
@fernandor777 where are we with the review for this? We have been waiting for a week now.

**Comment by taba90** [comment]
closing this issue since it has been with this https://github.com/geosolutions-it/geoserver/issues/219.
