### ISSUE TITLE
Review INSPIRE training material

### ISSUE THREAD

**Issue by nmco** [geosolutions-it/geoserver#242]
To clarify with @simboss:
1. Where is the updated training material for review?
1. Should we update the existing material whit the new Smart Data Loader and Features Templating?
1. Looks like there will not be an INSPIRE conference this year.

**Comment by simboss** [comment]
1. I should have given you alla the info, please report them here
2. If the version we are using (2.18), allows it, yes. If not, let's do it again and let's make it clear this won't work with the training.
3. Then let's do something ourselves

**Comment by nmco** [comment]
Created a [dedicated issue](https://github.com/geosolutions-it/geoserver/issues/244) for updating the training material with Smart Data Loader and Features Templating.

Spreadsheet about what to review available [HERE](https://docs.google.com/spreadsheets/d/1CSjRmUtT4RHdI5rULVLjAHEyIKYIEOfShg5-IZshAo4/edit#gid=7). 

An automated build will build from Educational GitHub and publish the result [HERE](https://docs.geoserver.geo-solutions.it/draft/edu/en/).

The latest training material package is available [HERE](https://www.dropbox.com/s/l9a4mw7k1hib845/Jose%20Macchi%20-%20Training-Geoserver-2.18.x-20210326.zip?dl=1).

A fixed training package can be submitted [HERE](https://www.dropbox.com/request/IXXxAyWSuvsURqS17Cyg).

@taba90 we basically need to review [the complex features part of the training material](https://docs.geoserver.geo-solutions.it/draft/edu/en/complex_features/index.html), we need to validate that the information is still valid and that all the exercises work whit the new updated training package.

If we find any mistake in the training material let's fix it and submit a PR. Likewise for the training package.

What's your estimate for the review @taba90 ?

**Comment by taba90** [comment]
@nmco 
I think the part to review/modify are two:
the one about complex features and the one about INSPIRE support.

- The complex features section should be renamed as ComplexFeature support and the hale part will be a subsection. The smart data loader section will be added, as well as a features-templating one.

- In the INSPIRE part of documentation I would then mention that the flat geoJSON output is supported trough features-templating, and maybe also some info about the ogcapi support should be addedd? the module is currently still under heavy development so we might postopone it.
Estimate is **4 hours**

**Comment by nmco** [comment]
@taba90 I have turned this issue in an EPIC, currently we are only focusing in reviewing the the complex features section of the training material, please provide your feedback and estimate on that dedicated issue -> https://github.com/geosolutions-it/geoserver/issues/246 thx :smiley:.
