### ISSUE TITLE
Review complex features training material

### ISSUE THREAD

**Issue by nmco** [geosolutions-it/geoserver#246]

**Comment by taba90** [comment]
- Turn the HALE part in a subsection.
- add a subsection coveraging SmartDataLoader and FeaturesTemplating.
Estimate is 2,5 - 3 hours

**Comment by nmco** [comment]
@taba90 this is a simple review we are aiming for here not a re-factoring, there is two dedicated issues for that re-factory under this EPIC.

What we need to do here is:
- Read the [Complex Features with GeoServer and HALE](https://geoserver.geo-solutions.it/educational/en/complex_features/index.html) portion of the training, fix any invalid or wrong information.
- Take note of any significant improvement we need to add, put a list on this issue, we will add them later.
- Execute the exercises and validate that they still work whit the updated training package.

**Comment by nmco** [comment]
Go ahead, the review should be done by Monday.

**Comment by taba90** [comment]
@nmco the data package misses a postgres/bin folder needed from postgis_start.bat to run.
Due this I was able to test only the stations use case tutorial which works fine. I still need to test the landcover and GeoSCiMil examples.

**Comment by nmco** [comment]
@simboss as per @taba90 comment above looks like the training package (downloaded from [HERE](https://www.dropbox.com/s/l9a4mw7k1hib845/Jose%20Macchi%20-%20Training-Geoserver-2.18.x-20210326.zip?dl=1)) is corrupted. Which is strange since this would mean that no exercise involving PsotgreSQL is passing ...

I see two options:
- We are using the wrong training package.
- It's indeed corrupted, in that case can you give a link to download the previous version?

Thank you!

**Comment by simboss** [comment]
please, define corrupted.

**Comment by taba90** [comment]
All the tutorial examples works fine with the provided data, geoserver instance and hale.
I would only change the download url for Hale from the one existing (that points to a version 4.0 that is not supported by the GeoServer AppSchema plug-in) to the[ github hale download page ](https://github.com/halestudio/hale/releases/tag/3.5.0) where the version 3.5 is still available for the download

**Comment by simboss** [comment]
@nmco can you update the [master plan](https://docs.google.com/spreadsheets/d/1CSjRmUtT4RHdI5rULVLjAHEyIKYIEOfShg5-IZshAo4/edit#gid=7) document?

**Comment by nmco** [comment]
@simboss done.
