### ISSUE TITLE
[GEOS-9937] Name of styles with colons are incorrect in REST API

### ISSUE THREAD

**Issue by nmco** [geosolutions-it/geoserver#257]
https://osgeo-org.atlassian.net/browse/GEOS-9937

**Comment by nmco** [comment]
Let's follow the following workflow:

1. Time-box the initial investigation of the issue to 2 hours.
2. Clarify the context of the task, make sure you have everything needed to move on.
3. Provide a plan and estimate to handle the reported issue, report on the issue.
4. Wait for the green light from the PM before moving on with the implementation.

**Comment by shadab-geo** [comment]
@nmco From the current implementation, it looks that anything present before the colon in style name is considered as a workspace name. It proceeds even if the workspace with the given name is not present. I have a solution where it can consider assigning workspace only if one with the given name exists. I believe overall it would take around 1 hour to implement and test it with various scenarios. should I go ahead and implement it?

**Comment by nmco** [comment]
Makes sense for me, I would say go ahead and submit the PR for review.

**Comment by nmco** [comment]
Pull requests available here:
https://github.com/geoserver/geoserver/pull/5231

@dromagnoli can you check my comment on the PR?

**Comment by nmco** [comment]
@shadab-geo let's wait for @dromagnoli | community feedback on this one.

**Comment by nmco** [comment]
Unblocked as per @dromagnoli reply on the PR.

**Comment by nmco** [comment]
JIRA ticket:
https://osgeo-org.atlassian.net/browse/GEOS-9937

**Comment by shadab-geo** [comment]
PR: 
https://github.com/geoserver/geoserver/pull/5244
Backport: https://github.com/geoserver/geoserver/pull/5247
