### ISSUE TITLE
Simplified property access in Features-templating plug-in

### ISSUE THREAD

**Issue by taba90** [geosolutions-it/geoserver#269]
Context: there  is the need to be able to use property names referring directly to the tableNames and column names present in the underlying database.

Plan: 

- A DuplicatingBuilderVisitor will need to visit the builder tree and map the simplified  PropertyName/Xpath function found in the DynamicBuilders, Sources or Filters, to the proper path. This needs to be done before the property names are validated so as soon as the builder tree is produced. 

- To be able to map to valid property names, we need access in the visitor to the FeatureTypeMapping and then check if the AttributeMapping OCQL Expression (or the sourceType in the FeatureTypeMapping) is equal to a part of the simplfied propertyName, and in case retrieve the target xpath. 

The resulting builderTree will have the updated property names and will be cached, retrieved and applied as usual.
The estimate for this is 2 days

**Comment by nmco** [comment]
We need to define the final syntax by taking the stations use case GeoJSON template and translate the properties from GML to domain properties. The example we used for our discussion @taba90:
```
{
    "$VendorOptions": "flat_output:$${env('flat_output','false')};separator:.",
    "type": "FeatureCollection",
    "features": [
        {
            "$source": "Stations"
        },
        {
            "Identifier": "${id}",
            "geometry": "${position}",
            "properties": {
                "Name": "${common_name}",
                "Code": "$${strConcat('STATION-', xpath('code'))}",
                "Location": "$${toWKT(xpath('position'))}",
                "Observations": [
                    {
                        "$source": "Observations"
                    },
                    {
                        "Timestamp": "${time}",
                        "Value": "$${strConcat(strConcat(xpath('value'), ' '), xpath('parameter_id -> Parameters.param_unit'))}",
                        "Type": "${child_id -> Parameters.param_name}"
                    }
                ]
            }
        }
    ]
}
```
The reverse mapping will be based on the App-Schema mappings.

When defining a templating the user should be able to validate against a layer (for example like we do for styles) the validation would basically implied requesting one features or more and encoded them.

We should extend the stations use case to support all the corner cases that we will need to deal with (recursive relationships, many to many relation ships and list of static values).

**Comment by taba90** [comment]
done and backported to 2.19.x
