### ISSUE TITLE
Features templating refact current code, implemented for the Builder tree creation

### ISSUE THREAD

**Issue by taba90** [geosolutions-it/geoserver#271]
Currently the builder tree is created trough an implementation of a [TemplateReader ](https://github.com/geoserver/geoserver/blob/ee4bd95ffe8dd862ac6375e332fc5fb6c6957582/src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/readers/TemplateReader.java#L10) interface and use the [BuilderFactory ](https://github.com/geoserver/geoserver/blob/a717c858fd786e81b024e87c199b40054b1beda1/src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/builders/BuilderFactory.java#L26) which is actually quite dummy, to build a specific Builder implementation.
The [JsonTemplateReader ](https://github.com/geoserver/geoserver/blob/f373df54f7587304ed61a32d1532b822e080ceb5/src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/readers/JSONTemplateReader.java) does a lot of conditional statements to recognize which builder needs to be implemented instead of delegating everything to Factory o a Builder class.
A plan to improve the current code is the following:

- Create a TemplateReaderFinder that on the basis of the output format will provide the correct template reader. Currently the Reader is directly create in the [TemplateWatcher ](https://github.com/geoserver/geoserver/blob/f373df54f7587304ed61a32d1532b822e080ceb5/src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/configuration/TemplateWatcher.java#L37) and this needs a change also to simply support other type of output formats.
- Create a TemplateBuilderMaker that will be able to create the correct template builder on the basis of the values passed by the specific reader. This should simplify a lot the code in the JsonTemplateReader while making a better reusable class with respect to the current BuilderFacotry.

**Comment by taba90** [comment]
Result of brainstorm between @taba90 and @nmco on 20-04-2021

- We could refact the builder  tree to simply accept a string and return a string with template directive resolved.
- In this way we would have the ability to easily add support for xml output format since we would ignore the concept of attribute name that is present in json. 
- It would be necessary to delay filter, cql expression and property name parsing to the moment we start evaluating the builder tree.
Main problems:
- time consuming since a rewriting of many part of the plugin will be needed eg:
-  json template reading as we would need a more low level json parser then the one provided by jackson or to rebuild a string value concatenating attribute names and values provided as separated by the json parser; 
- backwards mapping that is currently relying on the possibility to have CQL expression already parsed when searching the expression to which the json path is poiting to; 
- output writing since the templated portion being evaluated would need to be parsed to extract expression and evaluate them against the feature; 
- the flat geojson output would need to be completely rewrote since it works by concatenating json attribute names; 
- validation we loose the possibility to validate propertyNames before caching the template. We would need to perform validation just before encoding features and this would also likely implies to parse filters and dynamic attribute twice to create a cql expression and then evaluate it;
- more problems for the possibility to add simplified property names in template: we cannot replace domain base property names before caching the template, this would need to happen every time features are encoded and might have an impact on performance.
- To be on the safe side an estimate for this task would be of 8 days: all the existing functionality would need to be retested carefully. Moreover the STAC plug-in is using few classes from the features-templating plug-in as a dependency and this would be something to take care of too.

**Comment by nmco** [comment]
So let's go whit the current approach, which is fine since:
- we don't foreseen a lot more formats apart from XML and JSON
- small refactoring will be done to avoid code duplication

The main drawback of the current approach is that there is not a decoupling between the format parsing and the builder tree business,  all builders will need to be sub-classed a specialized for each format.

**Comment by nmco** [comment]
The refactoring will be done while implementing the XML support.
