### ISSUE TITLE
Plan to implement Features-Templating UI and multiple templates supports

### ISSUE THREAD

**Issue by taba90** [geosolutions-it/geoserver#272]
@taba90 commented on [Wed Apr 21 2021](https://github.com/geosolutions-it/support/issues/1335)

- The template configuration will be stored in the MetadataMap. For each template entry will be defined: mimeType, an optional regex rule to be applied to a request and tell if the template match it, the template path or url.
- The Template are loaded from the [TemplateConfiguration ](https://github.com/geoserver/geoserver/blob/f373df54f7587304ed61a32d1532b822e080ceb5/src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/configuration/TemplateConfiguration.java#L29) (will be renamed in TemplateLoader) object that is a spring singleton managing the access to templates.
- The [getTemplate ](https://github.com/geoserver/geoserver/blob/f373df54f7587304ed61a32d1532b822e080ceb5/src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/configuration/TemplateConfiguration.java#L73) method will be modified to accept a Request object. The template layer configuration will be loaded from the FeatureTypeInfo, the rules will be extracted and applied to the request. The one matching it will cause the corresponding template to be loaded from cache or from the provided uri.
- if no regex rule is defined the template will be considered as the default one for the mimeType, and will be used in case other template rules entries doesn't match the request  or there is no other template for the specified mimeType.
- A new method cacheTemplate will be provided to allow caching templates right after a template configuration is saved.
- The UI will provide: 
   - a list of template entries identified by  the `template name`; the `mimeType`; the `regex rule`;
   - a `textEditor` where will be displayed the currently selected template where it would be possible to edit the selected template (if it is not loaded using an http url) we will reuse the existing one for SLD for XML templates, and needs to do some code modification for json json-ld ones based;
   - an `add new template button` that will make available input fields to define uri, regex rule and mimetype for a new template entry.
Things to double check:
- using the editor would mean to give also the possibility to edit the template. How to behave with the template file?
    I see two possible way of doing this: 
    - we copy in the geoserver data dir the template from the specified URI; 
    - we allow editing only template loaded from a file uri ( in that case geoserver needs write grants on the file) and disable it when 
       loading from URL
- Mime type field: should it be provided as separate in the configuration or should be extracted trough the regex?

This is how the UI might look like
![TemplateUI](https://user-images.githubusercontent.com/46672505/115839934-72154180-a41b-11eb-8a99-883469f1077d.PNG)

**Comment by nmco** [comment]
Meeting minutes 23-04-2021:
- Storing templates should follow the same approach we use for styles:
  - The templates should be stored locally inside the GeoServer data directory, inside a dedicated data directory.
  - A feature template can be global or workspace, this is just the structure of the feature template directly, any layer will be able to use any template.
  - When you define the template you have to explicitly say if it global and per workspace.
  - On the UI we can upload styles like we do for styles, or copy pasting, etc ...
- Creating, editing, deleting, ... features templates should be done on a dedicated page, not inside the layer page.
- On the layer page we only link the templates with the right service & operation, mime-type, query-parameter or HTPT header. A checkbox should allow us to define if a the value to compare is a regex or not. Similar to what we do a for Geofence rule. We will need a mock-up for this. POST payload should be supported wiht a string contains.

**Comment by nmco** [comment]
As we discuss @taba90 we will need to estimate also a tab to provide on the fly validation, similar to what we have for the SLD styles. The goal is to allow the user to select a template, edit it, and test it against a layer.
