### ISSUE TITLE
Clarify: TG Requirement 9 do we have any capabilities in GeoServer to support multiple languages?

### ISSUE THREAD

**Issue by nmco** [geosolutions-it/geoserver#277]
For reference:
_TG Requirement 9 The Extended Capabilities shall indicate the response language used for the GetCapabilities-Response: Depending on the requested language the value of the <inspire_common:ResponseLanguage> corresponds to the current used language. If a supported language was requested, <inspire_common:ResponseLanguage> shall correspond to that requested language. If an unsupported language was requested or if no specific language was requested <inspire_common:ResponseLanguage> shall correspond to the service default language <inspire_common:DefaultLanguage> (do we have any capabilities in GeoServer to support multiple languages?)

**Comment by dromagnoli** [comment]
We already do this with the only one supported language.
