### ISSUE TITLE
[Geoserver-users] Bug with custom legend for styles [SEC=UNOFFICIAL]

### ISSUE THREAD

**Issue by nmco** [geosolutions-it/geoserver#281]
Follow up with that thread on GS ML.

**Comment by zvrablik** [comment]
I have tested these steps

1. open styles
2. open style burg
3. select button add legend
4. select link Choose Image / choose existing image
5. select grass_fill.png image
6. select Auto-detect image size and type
7. widht height format got filled
8. check the SLD xml - the legend file is not added there, looks like not connected at all
I have checked the code http://github.com/geoserver/geoserver/blob/97f2445718ae01fdecf2dc8f0d1bd125734b4161/src/web/wms/src/main/java/org/geoserver/wms/web/data/ExternalGraphicPanel.java#L247-L275
and I don't see there any trigger to update the xml.

I have tested same functionality in 2.18.3 (using downloaded zip file) and I got same behavior.

To add image to the SDL xml content I have to click to the Insert Image icon above the xml text area.

I think there was never any connection. Is it possible this was implemented and removed in 2.18.3?

I have asked Michael Sexton for Geoserver version where he see this working.

**Comment by zvrablik** [comment]
Michael Sexton replied that he is using this functionality first time.
I am still not sure if this is bug as I have not found any implementation in the autodetect image size and type which should create or update the graphics in the sld xml text area.
That is all I managed in one hour.
@nmco  Should I continue?

**Comment by aaime** [comment]
The custom legend does not go in the sld, but in the xml file on the side of the SLD. There are always two files:
* a "styles\stylename.xml" file, which contains the configuration of the style
* a "styles\stylename.sld" (or css, or ysld, or whatever is the extension of the style language being used) that contains the actual style.
