### ISSUE TITLE
UI pending small fixes

### ISSUE THREAD

**Issue by nmco** [geosolutions-it/geoserver#288]
Meeting with @taba90  01-06-2021:
- [ ] The editor is already JSON and XML sensitive, but we should make it also possible to highlight features templating terms.
- [ ] Validation needs to be reviewed and clarified. We will have different types of validations. It shoudl be included on the template preview.
- [ ] Template preview UI formatting needs to be fixed:
   - [ ] We should only display the name of workspace or feature type (remove the WorkspaceInfoImpl).
   - [ ] The example output should be formatted.
   - [ ] It should be possible to provide an CQL filter that will select the features that will be used for the preview.
   - [ ] Needs a button for the validation.
   - [ ] We should not use a WFS query but instead query a feature collection directly.
   - [ ] Ideally the UI should allow us to preview like the style, but this will be done only if time remains:
![image.png](https://images.zenhubusercontent.com/5cd43b4f3df15f5bbe3b2822/7a1331f4-685e-4175-8a38-bb2ef0e63e51)
- [ ] When deleting make sure to add a warning, for example when deleting a template if it used by any layer a warning should be displayed and the user needs to click in OK to finish the action.
- [ ] Layers binding:
  - [ ] There should be a better separation between the rules display and rule addition.
  - [ ] There should be a info panel explanation the dedicated CQL functions that can be used.
  - [ ] How to bind a rule to a specific service and operation.
  - [ ] We need also to vouch for POST requests, looks it's already the case.

**Comment by taba90** [comment]
made a pr on main for the UI. https://osgeo-org.atlassian.net/browse/GEOS-10153
