### ISSUE TITLE
Organize periodic code sprints for bug fixing/security

### ISSUE THREAD

**Issue by aaime** [geosolutions-it/geoserver#309]
@simboss would like us to organize periodic code sprints to address outstanding bugs and security issues (e.g., nontrivial dependabot upgrades).
We already found that one day a month is not very productive, we get started and end up leaving tasks incomplete. We probably need to pack 2-3 days every N months instead.

**Comment by aaime** [comment]
One of the items to discuss is how we assign tasks... right now we have a collection of items that have been deemed to be interesting, but not sure we have a list of easy tasks, that we could throw at less experienced devs.

**Comment by aaime** [comment]
Another one is security issues, failing dependabot PRs that need a different version for upgrade, or API changes that need to be handled, and so on.

**Comment by aaime** [comment]
Meeting notes:
- 2 days back to back, every 2 months. Last Thu/Fri of the month.
- Andrea to select which issues have a chance of being solved quickly
- Andrea/Nuno to create issues in Kanban board and assign tickets to people (this to be done on Monday)
- Use the Kanban board, put them in a dedicated epic, so that people can fetch them from the ready column
- Prioritize reviews to allow closing tasks. Cross review. First review cross among developers, and then Andrea and Daniele to do a final pass? 
- Who: Marco, Fernando, Daniele, Andrea? 8 work/days for one sprint. Shadab/Yalin a bit too green for the moment.
- Where to find issues: Jira, Depedendabot PRs, Security issues in a private repository (the smaller ones, not the large one).

**Comment by simboss** [comment]
can we close this one?

**Comment by nmco** [comment]
Yes, we have organized this with @aaime.
