### ISSUE TITLE
[GEOS-10218] GetFeatureInfo documentation example template generates invalid JSON

### ISSUE THREAD

**Issue by nmco** [geosolutions-it/geoserver#311]
https://osgeo-org.atlassian.net/browse/GEOS-10218

**Comment by nmco** [comment]
@shadab-geo didn't reproduce the problem. Please update the JIRA ticket with your feedback @shadab-geo.

**Comment by shadab-geo** [comment]
I got the clarification of the problem on the Jira ticket, I agree that the 'properties' part should be changed as per suggestion. Should I update it? @nmco

**Comment by shadab-geo** [comment]
PR merged: https://github.com/geoserver/geoserver/pull/5272
