### ISSUE TITLE
[Geofence] Implement transactional REST endpoint for the update or rules

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/geoserver#312]
Geofence module provides distinct endpoints to delete and create rules. Since an update is composed of delete+create this poses a severe risk of inconsistencies in case one of the two requests fail. 

We want to implement a single, transactional, update REST API endpoing, similar to what the standalone version [already implements](https://github.com/geoserver/geoserver/blob/main/src/extension/geofence-server/src/main/java/org/geoserver/geofence/server/rest/RulesRestController.java).

The endpoint will receive the new set of rules and will grant either a commit (new rulesfully applied) or a rollback (previous rules are kept), without any active involvement from the client.

@simboss this will be a much better solution for GeoNode too. For GN 3.2.x we have implemented a dump and rollback procedure client side, but it's far from ideal (one for all we need to dump the rules for each update). 3.3.x and master will adopt this new endpoint instead.
A rough estimate from @etj is 1 / 2 days.

**Comment by simboss** [comment]
I am happy to go ahead with this for 3.3.x and master ( I presume).

This will give us breathing room to decide wether or not we are going to perform a much broader refactor which involves creating a specific Geoserver RAM for GeoNode as per [this issue](https://github.com/geosolutions-it/geoserver/issues/187).

**Comment by giohappy** [comment]
Please @etj plan the work for this and let me know when we're ready to go.

**Comment by giohappy** [comment]
completed in https://github.com/geoserver/geoserver/pull/6072
