### ISSUE TITLE
[WPS download] Fix output filename extension for GeoPackage format

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/geoserver#313]
When GeoPackage is requested as download format (mime type `application/geopackage+sqlite3`) from WPS Download, the output filename is created with `.geopackage+sqlite3` extension. It should be changes to `.gpkg` since this is the expected extension for many applications (e.g. QGIS).

**Comment by aaime** [comment]
File extension is established around here:
https://github.com/geoserver/geoserver/blob/2.19.x/src/extension/wps-download/src/main/java/org/geoserver/wps/gs/download/VectorDownload.java#L267

which should be calling a method overridden for the purpose of giving a ".gpkg" extension:
https://github.com/geoserver/geoserver/blob/2.19.x/src/extension/wps-download/src/main/java/org/geoserver/wps/gs/download/GeopkgPPIO.java#L69

So hum... why are we getting a different one?
I'm guessing something is happening around here:
https://github.com/geoserver/geoserver/blob/2.19.x/src/extension/wps-download/src/main/java/org/geoserver/wps/gs/download/DownloadProcess.java#L425

**Comment by simboss** [comment]
@dromagnoli we need your help on this.

Ping me tomorrow please.

**Comment by dromagnoli** [comment]
@simboss ping :)

**Comment by simboss** [comment]
As per our chat @dromagnoli, please, have a stab at this and let me know how much time you think you need to fix it.

We need this as back as 2.19 as it's a fix.

**Comment by dromagnoli** [comment]
yep @simboss .
I'm setting up the machinery locally to see what is going on.
I should be back with an estimate by monday.

**Comment by dromagnoli** [comment]
@simboss I would say 0.5 - 1 day to check for all corner cases and eventual regressions and add tests

**Comment by simboss** [comment]
@dromagnoli go ahead then and backport this to 2.19.

**Comment by dromagnoli** [comment]
fix merged to main.
backports (2.20.x and 2.19.x) in progress

**Comment by dromagnoli** [comment]
backports merged
