### ISSUE TITLE
WMS GetCapabilities not returning the workspace prefix inside style names in 2.19.x

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/geoserver#315]
MapStore expects to receive the the workspace prefix inside the style name returned by the GetCapabilities. It used to work in 2.18.x, even for GC requests toward workspaced services.
For example [this request](https://stable.demo.geonode.org/geoserver/geonode/Major_Roads0/ows?service=WMS&version=1.3.0&request=GetCapabilities) returns

```
Style>
  <Name>geonode:Major_Roads0</Name>
  <Title>A dark yellow line style</Title>
  <LegendURL width="20" height="20">
	<Format>image/png</Format>
	<OnlineResource xmlns:xlink="http://www.w3.org/1999/xlink" xlink:type="simple" xlink:href="https://stable.demo.geonode.org/geoserver/geonode/Major_Roads0/ows?service=WMS&amp;request=GetLegendGraphic&amp;format=image%2Fpng&amp;width=20&amp;height=20&amp;layer=Major_Roads0"/>
  </LegendURL>
</Style>
```

2.19.x doesn't return the workspace prefix anymore. A similar [request](https://development.demo.geonode.org/geoserver/geonode/states/ows?service=WMS&version=1.3.0&request=GetCapabilities&access_token=lAS7Yx85zi4jqFgqQXyNaDhYv2E8EN)  returns

```
<Style>
  <Name>states</Name>
  <Title>A dark yellow polygon style</Title>
  <LegendURL width="20" height="20">
	<Format>image/png</Format>
	<OnlineResource xmlns:xlink="http://www.w3.org/1999/xlink" xlink:type="simple" xlink:href="https://development.demo.geonode.org/geoserver/geonode/states/ows?service=WMS&amp;request=GetLegendGraphic&amp;format=image%2Fpng&amp;width=20&amp;height=20&amp;layer=states"/>
  </LegendURL>
</Style>
```

Is this behaviour expected? Is the change on 2.19.x done on purpose?

**The missing prefix breaks MapStore's Style Editor logic**.

**Comment by giohappy** [comment]
@aaime can you shed some light on this?

**Comment by aaime** [comment]
The 2.19.x behavior is the correct one, if you're requesting on a workspace-specific capabilities document, all names must be de-qualified, including style ones. It's something we fixed recently.

**Comment by giohappy** [comment]
thanks @aaime.
So MapStore built a functionality on top of a wrong behaviour of previous GS versions...

**Comment by allyoucanmap** [comment]
@giohappy @aaime I was working to improve the client but there is a case where I'm not able to recognize the correct workspace of a style.
See this comment https://github.com/GeoNode/geonode-mapstore-client/issues/519#issuecomment-933344224
