### ISSUE TITLE
OGC-API-Features service needs link to metadata, bulkdownload and predefined download

### ISSUE THREAD

**Issue by PB-GNM** [geosolutions-it/geoserver#328]
I'm doing a research on the applicability of Geoserver OGC-API-Features for INSPIRE.
One of the INSPIRE requirements is to give links to metadata, bulk downloads and predefined downloads.
It is a recommendation in the [OGC part 1 specification](http://docs.opengeospatial.org/is/17-069r3/17-069r3.html#rec_core_fc-md-descriptions) and a requirements in the draft [guideline for setting up an INSPIRE Download service based on the OGC API-Features standard](https://github.com/INSPIRE-MIF/gp-ogc-api-features/blob/master/spec/oapif-inspire-download.md).
 
This guideline states the requirement for a [link to the metadata of the data set](https://github.com/INSPIRE-MIF/gp-ogc-api-features/blob/master/spec/oapif-inspire-download.md#metadata-elements-of-the-data-set), a [link to the bulkdownload](https://github.com/INSPIRE-MIF/gp-ogc-api-features/blob/master/spec/oapif-inspire-download.md#84-requirements-class-inspire-bulk-download-) and a [link to a predefined download](https://github.com/INSPIRE-MIF/gp-ogc-api-features/blob/master/spec/oapif-inspire-download.md#81-requirements-class-inspire-pre-defined-data-set-download-oapif--).

These links should be added to the other links that are given per collection. Could this be implemented in Geoserver? The user interface is already adjusted to this, but unfortunately it has no effect in the list of links for the collections.
![image](https://user-images.githubusercontent.com/80040145/157433029-686ce669-76bc-41c3-8e4a-c5fa11aa3c0f.png)

Best regards,
Pieter Bresters,
Geonovum, Netherlands

**Comment by aaime** [comment]
Moved to https://osgeo-org.atlassian.net/browse/GEOS-10415
