### ISSUE TITLE
Json array contains GeoServer/GeoTools function implementation

### ISSUE THREAD

**Issue by fernandor777** [geosolutions-it/geoserver#333]
## Target
We need to provide a function that checks the provided value exists inside a JSON field inner array.  The implemented function should be translated to SQL filter to be executed by the database engine.  Initial database native support will be added to Oracle and Postgresql databases.

JVM runtime evaluation support is required as well, for not native SQL supported stores.

## Implementation
Function name: ```jsonArrayContains```
- Receives as parameters:
  - The JSON attribute.
  - The field json path expression.  This expression needs to be aligned with the one used on the [JsonPointerFunction filter function](https://github.com/geosolutions-it/geotools/blob/8341ff84b525d2c2b239273546639139256f3ac9/modules/library/main/src/main/java/org/geotools/filter/function/JsonPointerFunction.java#L35).
  - The value to check.
- Returns boolean, true or false after evaluation.  Returns true only of the provided value is contained in the json array, otherwise returns false.

The expression format:
```
jsonArrayContains(<DB_COLUMN_NAME>, <JSON_PATH>, <EXPECTED_VALUE>)
```
Expression example:
```
jsonArrayContains(OPERATIONS, '/operations/operation_name', 'OP1')
```

The new function class could be named ```JsonArrayContains```, will be located on the ```gt-main``` GeoTools module at the same package level as [JsonPointerFunction class](https://github.com/geosolutions-it/geotools/blob/8341ff84b525d2c2b239273546639139256f3ac9/modules/library/main/src/main/java/org/geotools/filter/function/JsonPointerFunction.java#L35) and needs to extends the [function expression class](https://github.com/geosolutions-it/geotools/blob/f66689b5305eaf381e21dc2feec8011138d4cb24/modules/library/main/src/main/java/org/geotools/filter/FunctionExpressionImpl.java#L41).

### Database native execution implementation hints
For Oracle database we would need to perform a filter to SQL transformation in the [same fashion as JsonPointer function](https://github.com/geosolutions-it/geotools/blob/1f279f9bdf418dbabe5951359e2c960dbb3fa45f/modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/FilterToSqlHelper.java#L665).  This transformation should be [located at Oracle filter to sql implementation class](https://github.com/geosolutions-it/geotools/blob/a6c624c69beff4748d3c705d8cb2783ec7f42319/modules/plugin/jdbc/jdbc-oracle/src/main/java/org/geotools/data/oracle/OracleFilterToSQL.java#L84).

The resulting SQL [will use the JSON_EXISTS function](https://docs.oracle.com/en/database/oracle/oracle-database/12.2/adjsn/condition-JSON_EXISTS.html#GUID-D60A7E52-8819-4D33-AEDB-223AB7BDE60A) to evaluate the value is present at least once on the json array.

Oracle filter to SQL translation example:
```
json_exists(OPERATIONS, '$.operations?(@ == "OP1")')
```

For Postgresql implementation [the FilterToSqlHelper class is the target.](https://github.com/geosolutions-it/geotools/blob/1f279f9bdf418dbabe5951359e2c960dbb3fa45f/modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/FilterToSqlHelper.java#L116).  The [Postgresql JSONb ```@>``` operator](https://www.postgresql.org/docs/10/functions-json.html#FUNCTIONS-JSONB-OP-TABLE) will be used.
Postgresql filter to SQL translation:
```
OPERATIONS @> '{"operations": ["OP1"]}'
```

We can take inspiration and guidelines from the implemented JsonPointerFunction, some codepointers:
- ```org.geotools.filter.function.JsonPointerFunction```
- ```org.geotools.data.postgis.FilterToSqlHelper#encodeJsonPointer```
- ```org.geotools.data.postgis.PostgisFilterToSQL#visitBinaryComparisonOperator```

The tests (including online tests against the underlying databases oracle and postgresql):
- Add a test for the new function, in the same package and using the [same approach as the JsonPointer test](https://github.com/geotools/geotools/blob/a7cbcb6fee1160ad6ccab2df63fd83a633373fb3/modules/library/main/src/test/java/org/geotools/filter/function/JsonPointerFunctionTest.java#L27).
- [Oracle filter to sql test.](https://github.com/geosolutions-it/geotools/blob/f5b836501318cdf542bb8fc3befa2c24e7f2826c/modules/plugin/jdbc/jdbc-oracle/src/test/java/org/geotools/data/oracle/OracleFilterToSqlTest.java#L34)
- [Postgresql filter to Sql test.](https://github.com/geotools/geotools/blob/35fa3739cea96bfaa670fc65bc3db7586a6c701e/modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostgisFilterToSQLTest.java#L256)
 
For online test we can get example from the Json onlin test for postgis to create the jsonArrayContains online test for Oracle and Postgresql.  The new online tests classes should be created at the same package level on ```gt-jdbc-oracle``` and ```gt-jdbc-postgis``` modules.
Json online test example:
- https://github.com/geotools/geotools/blob/0d475aea085891ae470eeb71fdd5b0aba20f947f/modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostGISJsonTestSetup.java#L26
- https://github.com/geotools/geotools/blob/0d475aea085891ae470eeb71fdd5b0aba20f947f/modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostGISJsonOnlineTest.java#L42

Oracle online test example:
- https://github.com/geotools/geotools/blob/aecfbcaff5e01f3d35aaf38826de43b051cd4603/modules/plugin/jdbc/jdbc-oracle/src/test/java/org/geotools/data/oracle/OracleNativeFilterOnlineTest.java#L22
- https://github.com/geotools/geotools/blob/f922f0bdd19e32b9648ad644af2a1eed75417964/modules/plugin/jdbc/jdbc-oracle/src/test/java/org/geotools/data/oracle/OracleNativeFilterTestSetup.java#L23

### Oracle testing instance
- host:  starogc-dev-oracle.emsa.geo-solutions.it
- port: 1521
- sid: oracle
- user:  RTMPS_TEST
- password: RTMPS@!TWO3
- table: STATIONS
- column: OPERATIONS

Operations JSON examples:
```
{"operations": ["OP1", "OP2", "OP3"]}
{"operations": ["OP2", "OP3"]}
{"operations": ["OP2"]}
```

Estimate: 8 H

**Comment by nmco** [comment]
Repeated by this one: https://github.com/geosolutions-it/emsa-ogc/issues/1029
