### ISSUE TITLE
Disk Quota goes crazy sometimes

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/geoserver#347]
We're experiencing critical issues with Disk Quota in Geoserver for GeoNode, also reported by users, which often require either resetting (disable/enable) or totally disabling it.
The most recent cases happened with Geoserer 2.20.7, but for the moment there's no evidence that this is the only affected version.
The problem surfaces with the following two prominent effects:

- very high-frequency queries to the DB (fig.1), in the number of thousands of reqs/sec
- the disk quota manager reports false negative quota values (fig.2)

The most recent cases were fixed by disabling and then enabling Disk Quota again, but sometimes this isn't enough.

Unfortunately, we don't have stack traces or memory dumps at the moment.
Geoserve logs do not report anything suspicious.

The configuration of Geoserver for GeoNode 2.20.7 is available [here](https://github.com/GeoNode/geoserver-geonode-ext/tree/2.20.7).

**fig. 1**
![disk_quota_queries](https://user-images.githubusercontent.com/571129/231123085-bd513e4f-4aaa-4188-af7a-59b47783cc55.png)

**fig. 2**
![disk_quota_error](https://user-images.githubusercontent.com/571129/231123160-025ef4cc-e4d9-4dfc-b743-d77c20657741.png)

**Comment by giohappy** [comment]
>@giohappy are you using clustered GeoServers?

@nmco no

**Comment by aaime** [comment]
@giohappy how does the tile locking mechanism setup look like then?

![image](https://user-images.githubusercontent.com/325433/231828401-b8f1270f-5c87-4d76-b963-3a34344b1cd0.png)

**Comment by giohappy** [comment]
>@giohappy how does the tile locking mechanism setup look like then?

@aaime it's disabled

![Screenshot_20230413_194739.jpg](https://user-images.githubusercontent.com/571129/231842461-4179431f-e548-41ca-ad3a-3dee720bd38b.jpg)

The typical meta size is 512

**Comment by aaime** [comment]
Locking disabled is a likely cause of the issue... two or more metatiles can be produced at the same time, they will update the disk quota concurrently, causing both the race conditions during inserts, the quota values being wrong, and making the CPU run a lot hotter than necessary (as multiple threads are all computing, slicing and compressing the tiles for the same meta-tile).

**Comment by giohappy** [comment]
The lock was configured this way https://github.com/GeoNode/geoserver-geonode-ext/commit/03a4017a745d770ef4c1f3da1e6da40acf2e4881

@afabiani says this change was agreed with you since the locking mechanism wasn't working fine at the time.

Have things changed meanwhile? Should we leave the default (GlobalLocking I guess) in 2.20.7 and 2.23.0?

**Comment by aaime** [comment]
Nothing changed in the meantime. I believe we discussed NIO locking, which was indeed not working due to NFS faults, in-memory locking is safe and should be used instead. But I might remember things wrong...

**Comment by aaime** [comment]
Wrote a "solutions" document about this issue here: https://docs.google.com/document/d/1Xpmi1i6_suK0oW8jSS-iBqhFV6wr__ulBoPW3HlSdcQ/edit#

**Comment by giohappy** [comment]
Thx @aaime. We will change the default configuration of Geoserver for GeoNode to use the in-process locking by default.
