### ISSUE TITLE
Implement REST API to manage URL checks

### ISSUE THREAD

**Issue by aaime** [geosolutions-it/geoserver#353]
Possibly, but not necessarily, based on the existing ACL controllers family of REST APIs

**Comment by knyambee** [comment]
Hello @aaime, I would love to take this up. Kindly share more details.

**Comment by aaime** [comment]
Oh sorry, this has been fixed already: https://github.com/geoserver/geoserver/pull/7582

This is not the GeoServer official ticket tracker, we use it as a secondary one for GeoSolutions employees.
If you're looking for tasks that you can take on, check out the official Jira ticket tracker instead: https://osgeo-org.atlassian.net/jira/software/c/projects/GEOS/issues

**Comment by knyambee** [comment]
Thanks for the feedback. Well noted.

At your service,
Kelvin Nyambe
